config/routes.rb
Sepia::Application.routes.draw do
  root to: 'photos#index'

  resources :photos, only: [:index]
  resources :albums, only: [:index, :show, :create, :update, :destroy] do
    resources :photos, controller: 'albums/photos', only: [:create], constraints: { format: 'json' }, format: true do
      delete :destroy, on: :collection
    end
  end
  resources :users,  only: [:show, :update, :index]

  namespace :public do
    resources :albums, only: [:show]
  end

  # for devise
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # for oauth2 api
  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end
  mount Sepia::API, at: '/api'

  # TODO : authenticate
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  if Rails.env.production?
    match '*not_found', to: 'application#render_404', via: :all
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to  :user
  has_many :albums_photos, class_name: 'AlbumsPhotos', inverse_of: :album, dependent: :destroy
  has_many :photos, through: :albums_photos

  scope :public, -> { where(public: true) }

  validates :name, presence: true

  def owner? user
    user.id == self.user_id
  end
end

app/controllers/albums/photos_controller.rb
class Albums::PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_album

  def create
    @photos = current_user.photos.where(id: params[:photo_ids]) if params[:photo_ids]
    if @album && @photos && !@photos.empty?
      begin 
        ActiveRecord::Base.transaction do 
          @album.photos.concat(@photos)
        end
      rescue => e
        logger.warn e
        @error = e
      end
    end
  end

  def destroy
    @photos = current_user.photos.where(id: params[:photo_ids]) if params[:photo_ids]
    if @album && @photos && !@photos.empty?
      begin
        ActiveRecord::Base.transaction do 
          @album.photos.destroy(@photos)
        end
      rescue => e
        logger.warn e
        @error = e
      end
    end
  end

  private
  def set_album
    @album = current_user.albums.where(id: params[:album_id]).first
    head :not_found unless @album
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  include Paginate
  before_action :authenticate_user!
  before_action :check_viewable, only: [:show]
  before_action :check_own, only: [:update, :destroy]

  def index
    @albums =
      current_user
      .albums
      .eager_load(:photos)
      .page(params[:page] || 1)
      .per(Settings.albums.per_page)
      .order('albums.created_at DESC')
    @all_count = current_user.albums.size
  end

  def show
    @album = Album.find(params[:id])
    @photos = @album.photos
                      .page(params[:page] || 1)
                      .per(Settings.photos.per_page)
                      .order('posted_at DESC')
    @all_count = @album.photos.size
    render layout: "public" unless @album.owner? current_user
  end

  def create
    @album = current_user.albums.create(album)
  end

  def update
    @album = current_user.albums.find(params[:id])
    album.each{ |(key, value)| @album.send("#{key}=", value) }
    @album.save!
  end

  def destroy
    @album = current_user.albums.find(params[:id])
    current_user.albums.destroy(@album)
  end

  private
  def check_own
    head :forbidden unless own_album? params[:id]
  end

  def check_viewable
    head :forbidden unless own_album?(params[:id]) or public_album?(params[:id])
  end

  def album
    params.require(:album).permit(:name, :public)
  end

  def public_album? id
    target = Album.find_by(id: id)
    target && target.public?
  end

  def own_album? id
    id && (album = Album.find_by(id: id)) ? current_user.id == album.user_id : false;
  end
end

app/views/albums/index.html.slim
ruby:
  per_page = Settings.albums.per_page
  current_page = (params[:page].try(:to_i) || 1)

h1 
  i.icon-film
  |  Your Albums

button.btn.btn-primary data-toggle="modal" href="#create-form"
  i.icon-plus

.row-fluid
  ul#albums.thumbnails
    - @albums.each do |album|
      li.album
        = link_to 'javaScript:void(0)', :'data-album-id' => album.id, class: 'album-trash' do
          i.icon-trash.icon-large
        = link_to url_for(album), class: "img-link" do
          .img-block
            - if album.photos.empty?
              span.simple
                = lazy_image_tag('/images/no-image.jpg', :'data-page' => 1)
            - else
              span.stack
                = lazy_image_tag(album.photos.first.thumbnail_url, :'data-page' => 1)
        h4.title id="title-header-#{album.id}"
          = link_to url_for(album) do
            span id="title-#{album.id}" = album.name
            = " (#{album.photos.size})"
        input type="text" id="title-edit-#{album.id}" style="display:none;"
        | &nbsp;
        i.btn.btn-link.icon-edit.title-edit data-album-id="#{album.id}"
        p.date = format_time(album.updated_at)

- if per_page * current_page < @all_count
  div#more
    = link_to 'Show more results', 'javaScript:void(0)', id: "load-link", :'data-current-page' => "#{current_page}", :'data-url' => "#{albums_path(format: :json)}", class: "btn"

#create-form.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" aria-hidden="true"
          | &times;
        h4
          | New Album
      .modal-body
        #errors
        = form_for Album.new, class: "form-horizontal" do |f|
          .form-group
            = f.label :name, class: "control-label span2"
            .span10
              = f.text_field :name, class: "form-control", placeholder: "your album's name..."
      .modal-footer
        a#create-submit.btn.btn-primary href="javaScript:void(0)"
          | Save

= javascript_include_tag "albums"

script#album-template type="text/template"
  li.album
    = link_to 'javaScript:void(0)', :'data-album-id' => '%{ id }', class: 'album-trash' do
      i.icon-trash.icon-large
    = link_to '%{ url }', class: "img-link" do
      .img-block
        span class='%{ stack_class }'
          = lazy_image_tag('%{ image_url }', :'data-page' => '%{ page }')
    h4.title id="title-header-%{ id }"
      = link_to '%{ url }' do
        span id="title-%{ id }" = '%{ name }'
        = " (%{ size })"
    input type="text" id="title-edit-%{ id }" style="display:none;"
    | &nbsp;
    i.btn.btn-link.icon-edit.title-edit data-album-id="%{ id }"
    p.date = '%{ updated_at }'

script#error-msg-template type="text/template"
  .alert.alert-danger
    button.close data-dismiss="alert"
      | &times;
    strong
      | %{ key } :
    | %{ message }

app/views/albums/show.html.slim
ruby:
  own_album = current_user && @album.owner?(current_user)
  per_page = Settings.photos.per_page
  current_page = (params[:page].try(:to_i) || 1)

- if own_album
  = link_to albums_path do
    i.icon-arrow-left
    | &nbsp; Back to album list
h1
  i.icon-film
  | &nbsp;
  = @album.name
- if own_album
  - if @album.public?
    input#album-visibility.switch-small type="checkbox" data-on="success" data-off="warning" data-on-label="public" data-off-label="private" data-album-id="#{@album.id}" checked="checked"
  - else
    input#album-visibility.switch-small type="checkbox" data-on="success" data-off="warning" data-on-label="public" data-off-label="private" data-album-id="#{@album.id}"

#photos style="clear: both;" data-album-id=params[:id]
  ul#polaroids
    - @photos.each do |photo|
        li
          div class="polaroid frame-#{photo.provider}" data-original-title=format_time(photo.posted_at) data-content==""
            i class="provider-icon #{icon_class(photo.provider)}"
            = link_to 'javaScript:void(0)', :'data-album-id' => params[:id], :'data-photo-ids' => [photo.id], class: 'photo-trash' do
              i.icon-trash.icon-large
            = link_to photo.fullsize_url, class: "display-link", rel: 'photo-group', title: photo.message do
              = lazy_image_tag(photo.thumbnail_url, class: 'img-photo', :'data-page' => 1)
            .message
              span.message-short == photo.message

- if per_page * current_page < @all_count
  div#more
    = link_to 'Show more results', 'javaScript:void(0)', id: "load-photo-link", :'data-current-page' => "#{current_page}", :'data-url' => "#{album_path(id: params[:id], format: :json)}", class: "btn"

script#photo-template type="text/template"
  li
    div class="polaroid frame-%{ provider }" data-original-title="%{ posted_at }" data-content=""
      i class="provider-icon %{ icon_class }"
      = link_to 'javaScript:void(0)', :'data-album-id' => "%{ album_id }", :'data-photo-ids' => "%{ photo_ids }", class: 'photo-trash' do
        i.icon-trash.icon-large
      = link_to '%{ fullsize_url }', class: "display-link", rel: 'photo-group', title: '%{ message }' do
        = lazy_image_tag('%{ thumbnail_url }', class: 'img-photo', :'data-page' => '%{ page }')
      .message
        span.message-short = '%{ message }'

- if own_album
  div#toggle-candidate
    i#toggle-candidate-icon.icon-double-angle-up.icon-3x
  #add-candidate data-url=photos_path(format: :json)
    #candidate-photos
      span#more-candidate
        = link_to 'more', 'javaScript:void(0)', id: "load-candidate-link", :'data-current-page' => 0, :'data-url' => "#{photos_path(format: :json)}", class: "btn"

script#candidate-template type="text/template"
  = lazy_image_tag('%{ thumbnail_url }', id: 'candidate-%{ id }', class: 'img-photo', :'data-photo-id' => '%{ id }', :'data-candidate-page' => '%{ page }')

= javascript_include_tag "albums"
= javascript_include_tag "photos"