config/routes.rb
Sepia::Application.routes.draw do
  root to: 'photos#index'

  resources :photos, only: [:index]
  resources :albums, only: [:index, :show, :create, :update, :destroy] do
    resources :photos, controller: 'albums/photos', only: [:create], constraints: { format: 'json' }, format: true do
      delete :destroy, on: :collection
    end
  end
  resources :users,  only: [:show, :update, :index]

  namespace :public do
    resources :albums, only: [:show]
  end

  # for devise
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # for oauth2 api
  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end
  mount Sepia::API, at: '/api'

  # TODO : authenticate
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  if Rails.env.production?
    match '*not_found', to: 'application#render_404', via: :all
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :user_id, :provider, :platform_id, :format, :message, :width, :height, :posted_at

  belongs_to :user
  has_many :albums_photos, class_name: 'AlbumsPhotos', inverse_of: :photo, dependent: :destroy
  has_many :albums, through: :albums_photos

  validates :user_id, presence: true
  validates :provider, presence: true
  validates :platform_id, presence: true, uniqueness: { scope: [:user_id, :provider] }
  validates :format, presence: true
  validates :posted_at, presence: true

  def fullsize_url
  end
  def thumbnail_url
  end
end

app/models/photo/facebook.rb
class Photo::Facebook < Photo
  include UseStore
end

app/models/photo/foursquare.rb
class Photo::Foursquare < Photo
  include UseStore
end

app/models/photo/google.rb
class Photo::Google < Photo
  include UseStore
end

app/models/photo/instagr_am.rb
class ::Photo::InstagrAm < Photo
  include UseStore
end

app/models/photo/pic_twitter.rb
class Photo::PicTwitter < Photo
  include UseStore
end

app/models/photo/twit_pic.rb
class Photo::TwitPic < Photo
  def fullsize_url
    "http://twitpic.com/show/full/#{self.platform_id}"
  end
  def thumbnail_url
    "http://twitpic.com/show/thumb/#{self.platform_id}"
  end
end

app/models/photo/use_store.rb
module Photo::UseStore
  extend ActiveSupport::Concern

  included do
    attr_accessible :fullsize_url, :thumbnail_url
    store :optional, accessors: [ :fullsize_url, :thumbnail_url ]

    validates :fullsize_url, presence: true
    validates :thumbnail_url, presence: true
  end  

end

app/controllers/albums/photos_controller.rb
class Albums::PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_album

  def create
    @photos = current_user.photos.where(id: params[:photo_ids]) if params[:photo_ids]
    if @album && @photos && !@photos.empty?
      begin 
        ActiveRecord::Base.transaction do 
          @album.photos.concat(@photos)
        end
      rescue => e
        logger.warn e
        @error = e
      end
    end
  end

  def destroy
    @photos = current_user.photos.where(id: params[:photo_ids]) if params[:photo_ids]
    if @album && @photos && !@photos.empty?
      begin
        ActiveRecord::Base.transaction do 
          @album.photos.destroy(@photos)
        end
      rescue => e
        logger.warn e
        @error = e
      end
    end
  end

  private
  def set_album
    @album = current_user.albums.where(id: params[:album_id]).first
    head :not_found unless @album
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include Paginate
  before_action :authenticate_user!

  def index
    @photos =
      current_user
      .photos
      .page(params[:page] || 1)
      .per(Settings.photos.per_page)
      .order('posted_at DESC')
    @all_count = current_user.photos.size
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
  ICON_CLASSES = {
    twitter: 'icon-twitter',
    facebook: 'icon-facebook',
    google_oauth2: 'icon-google-plus',
    instagram: 'icon-instagram',
    foursquare: 'icon-foursquare'
  }
  def icon_class provider
    ICON_CLASSES[provider.to_sym] || 'icon-question'
  end
end

app/views/photos/index.html.slim
ruby:
  per_page = Settings.photos.per_page
  current_page = (params[:page].try(:to_i) || 1)

- current_user.access_tokens.expired.each do |access_token|
  .alert.alert-error.fade.in
    button.close type="button" data-dismiss="alert"
      | &times;
    strong= "#{ t(access_token.provider) } Token Expired!!"
    | &nbsp; please 
    = link_to "refresh token", user_omniauth_authorize_path(access_token.provider)

h1
  i.icon-picture
  |  Your Photos

#photos
  ul#polaroids
    - @photos.each do |photo|
        li
          div class="rotate polaroid frame-#{photo.provider}" data-original-title=format_time(photo.posted_at) data-content==""
            i class="provider-icon #{icon_class(photo.provider)}"
            = link_to photo.fullsize_url, class: "display-link", rel: 'photo-group', title: photo.message do
              = lazy_image_tag(photo.thumbnail_url, class: 'img-photo', :'data-page' => 1)
            .message
              span.message-short == photo.message

- if per_page * current_page < @all_count
  div#more
    = link_to 'Show more results', 'javaScript:void(0)', id: "load-link", :'data-current-page' => "#{current_page}", :'data-url' => "#{photos_path(format: :json)}", class: "btn"

= javascript_include_tag "photos"

script#photo-template type="text/template"
  li
    div class="rotate polaroid frame-%{ provider }" data-original-title="%{ posted_at }" data-content=""
      i class="provider-icon %{ icon_class }"
      = link_to '%{ fullsize_url }', class: "display-link", rel: 'photo-group', title: '%{ message }' do
        = lazy_image_tag('%{ thumbnail_url }', class: 'img-photo', :'data-page' => '%{ page }')
      .message
        span.message-short = '%{ message }'
script
  | $('.alert').alert();